version: "3.9"
services:
  worker:
    build: .
    environment:
     - APP_ID=${APP_ID}
     - API_HASH=${API_HASH}
     - TG_BOT_TOKEN=${TG_BOT_TOKEN}
     - OWNER_ID=${OWNER_ID}
     - CHANNEL_ID=${CHANNE_ID}
     - CUSTOM_CAPTION=${CUSTOM_CAPTION}
     - START_MESSAGE=${START_MESSAGE}
     - PROTECT_CONTENT=${PROTECT_CONTENT}
